CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1)
OUTPUT_DIR: '/data/seongbin/ckpts/segmentation/PIDNet'
LOG_DIR: 'logs'
WORKERS: 3
PRINT_FREQ: 10
DATASET:
  DATASET: voc
  ROOT: /data/voc2012/
  NUM_CLASSES: 21
MODEL:
  NAME: pidnet_m
  NUM_OUTPUTS: 2
  PRETRAINED: "/data/seongbin/ckpts/segmentation/imagenet/PIDNet_M_ImageNet.pth.tar"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 256
  - 256
  BASE_SIZE: 400
  BATCH_SIZE_PER_GPU: 6
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 200
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.005
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16
TEST:
  IMAGE_SIZE:
  - 256
  - 256
  BASE_SIZE: 400
  BATCH_SIZE_PER_GPU: 1
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: ''
  OUTPUT_INDEX: 1
